### ISSUE TITLE
Capstone Progress Task List

### ISSUE THREAD

**Issue by KamiTopalyan** [KamiTopalyan/CapstoneProject#1]
- [x] Add capstone project to github
- [x] Create react project
- [x] Install all dependencies for a MERN stack
- [x] Create the folder structure
- [x] Start backend
- [x] Setup MongoDB
- [x] Connect to MongoDB though node.js
- [x] Create Mongoose models for user and passwords
- [x] Create the API with express.js
- [x] Implement required functions to manage the database

**Comment by KamiTopalyan** [comment]
Goals are finished
