### ISSUE TITLE
Capstone Progress Task List

### ISSUE THREAD

**Issue by KamiTopalyan** [KamiTopalyan/CapstoneProject#2]
- [x] Create user authentication and encryption
- [x] Start Front end
- [x] Make use of requests to the API and save them as JSON
- [x] Create a visual system that displays data from the password models
- [x] Separate each TSX code segements into separate components
- [x] Create page not found 
- [x] Create Input Fields 
- [x] Create password generator button
- [x] Create encryption for passwords entered
